### ISSUE TITLE
Create Boilerplate not working

### ISSUE THREAD

**Issue by raguay** [withfig/autocomplete#83] opened 2021-04-01 05:28 UTC
Just following the instruction works until `npm run dev`. The `npm run create-boilerplate` says there isn't a script with that name.

**Comment by falky97** [comment] 2021-04-01 05:42
hmmm. So weird.  I can't seem to reproduce. Can you make sure all the files have downloaded correctly? Maybe try re-running `npm install`.

Also what node version are you using?

![image](https://user-images.githubusercontent.com/4949076/113248692-4797f480-9272-11eb-8345-54895e9e9f36.png)

**Comment by raguay** [comment] 2021-04-01 07:00
okay, there isn't a ts-node-script referenced in the package.json file. I've never used Typescript before. Is there a tool set you have to install first?

**Comment by QuiiBz** [comment] 2021-04-01 08:45
`ts-node-script` is a cli from the `ts-node` package, which is installed in dev dependencies. Make sure you installed them with `npm i`. Also, could you provide us a screenshot of the error?

**Comment by raguay** [comment] 2021-04-01 10:47
Okay, I re-ran npm install and this time the ts-node-script is there. On
the initial run, it didn't install it. Not sure why. But, since it works
now, I can't give the screen shot. But, the message was just that there
isn't a ts-node-script command.

**Comment by QuiiBz** [comment] 2021-04-01 13:13
Strange, it should have worked the first time.

**Comment by raguay** [comment] 2021-04-01 13:54
I agree. Also, the husky library installed also the second time. It must not of installed the first time. I didn't see anything saying it didn't install. I wiped out the directory and started fresh. This time it worked all the way through. I've never had problems with npm installs before and I use it all the time. Weird.

**Comment by QuiiBz** [comment] 2021-04-01 14:25
Yes, very weird. Closing since it’s not related to Fig.

**Closed by QuiiBz** 2021-04-01 14:25 UTC

**Comment by cstrnt** [comment] 2021-04-01 15:43
@raguay could you please send me the output of `npm -v`

**Comment by raguay** [comment] 2021-04-02 01:39
npm -v                                                                08:38:49
7.6.3
