### ISSUE TITLE
Not compatible with windows

### ISSUE THREAD

**Issue by singhanshveer** [withfig/autocomplete#1182] opened 2022-04-24 07:50 UTC
Why is this app not compatible in windows? The company is missing out a larger target audience.

**Comment by fedeci** [comment] 2022-04-24 11:06
Duplicate of https://github.com/withfig/fig/issues/35

**Comment by fedeci** [comment] 2022-04-24 11:07
@singhanshveer as you can see in the linked issue we are adding both windows and linux support, you can subscribe to that issue to get updates on the development!

**Closed by fedeci** 2022-04-24 11:06 UTC
